#!/bin/sh
. /lib/functions/gl_util.sh

#[ $SEEN -gt 0 ] || exit 0

#This is the hidden button of AR300M
echo "$BUTTON ${ACTION}" > /dev/console

model=$(get_model)
if [ "$model" = e750 ];then
        kill -9 $(pgrep -f "switch_queue")
        switch_queue &
else
 	/usr/bin/switchaction &
fi
