#!/bin/sh

. /lib/functions/gl_util.sh

model=$(get_model)
[ "$model" != "b2200" ] && exit 0

getSectionNo(){
	SectionNo=`uci show samba|grep '$1'|sed -e "s/^.*\[\\(.*\)\].*$/\1/"`
	echo $SectionNo
}
read_only=$(uci get glconfig.samba.read_only)
[ -z "$read_only" ] && read_only=yes
blkdev=`dirname $DEVPATH`
device=`basename $DEVPATH`
hdorsd=`echo "$device" | grep -E '[sh]d*|mmcblk0*' `
label=`/usr/sbin/blkid -d /dev/$device|sed -n 's/.*LABEL="\([^"]*\)".*/\1/p'`
filesys=`/usr/sbin/blkid /dev/$device|sed -n 's/.* TYPE="\([^"]*\)".*/\1/p'`
mmc_share_exist=0

#vfat use ANSI label name
[ -z "$label" -o "$filesys" = "vfat" ] && label=$device

[ -n "$hdorsd" ] && {
	case "$ACTION" in
	add)
		[ "$model" = "mv1000" ] && [ "$device" = "mmcblk0p1" ] && exit 0 #mv1000 emmc mmcblk0p1 not setup as samba share
		[ -z "$filesys" -o "$filesys" = "swap" ] && exit 0 #must have file system and not swap
		[ "$label" = "rootfs" -o "$label" = "rootfs_data" ] && exit 0  #s1300 emmc rootfs and rootfs_data not setup as samba share
		#first loop the shares. If there is any duplicated entry, delte it first.
		i=$(uci show samba|awk 'NF{p=$0}END{print p}'|sed -e "s/^.*\[\\(.*\)\].*$/\1/")
		while [ "$i" -ge 0 ]
		do
			sharepath=$(uci get samba.@sambashare[$i].path)
			[ "$sharepath" = "/mnt/$label" ] && {
				uci delete samba.@sambashare[$i]
			}
			[ "$sharepath" = "/data" ] && mmc_share_exist=1
			i=$(( i-1 ))
		done

		mmcblk0=`echo "$device" |grep 'mmcblk0'`
		[ -n "$mmcblk0" -a "$mmc_share_exist" = "1" ] && exit 0
		uci add samba sambashare

		if [ -n "$mmcblk0" -a -n "$(mount | grep 'on /data')" ]; then
			if [ "$model" != "b2200" ];then
				uci set samba.@sambashare[-1].name="data"
			else
				uci set samba.@sambashare[-1].name="GL-Samba"
			fi
			uci set samba.@sambashare[-1].path="/data"
		else
			uci set samba.@sambashare[-1].path="/mnt/$label"
			uci set samba.@sambashare[-1].name="$label"
		fi

		if [ -n "$mmcblk0" ]; then
			[ "$model" != "b2200" ] && read_only=no
		fi
		uci set samba.@sambashare[-1].read_only=$read_only
		uci set samba.@sambashare[-1].guest_ok=yes
		uci commit samba
		/etc/init.d/samba restart
		;;

	remove)
		i=$(uci show samba|awk 'NF{p=$0}END{print p}'|sed -e "s/^.*\[\\(.*\)\].*$/\1/")
		while [ "$i" -ge 0 ]
		do
			sharepath=$(uci get samba.@sambashare[$i].path)
			d=$(uci get samba.@sambashare[$i].name)
			if [ ! -e "$sharepath" -o "$d" = "$label" ]
			then
				uci delete samba.@sambashare[$i]
			fi

			#in case /mnt/sda1 is used as folder, we should detect by mount point

			i=$((i-1))
		done
		uci commit samba
		/etc/init.d/samba restart
		;;
	esac
}

