#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=30
USE_PROCD=1

ssids_cb() {
        local ignore

        config_get ignore "$1" ignore

        [ "$ignore" = "1" ] && {
                uci set ssids.$1.disabled='1'
                return
        }

        uci set ssids.$1.disabled='0'
        uci set ssids.$1.trycount='0'
}

config_load ssids
config_foreach ssids_cb network
uci commit ssids
rm /etc/config/ssids_blacklist -rf
