#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done
    . /lib/functions/gl_util.sh
    model=$(get_model)
	flag=0
	#echo "model:$model" >/dev/console
	if [ "$model" = "mifi" -o "$model" = "x750" -o "$model" = "xe300" -o "$model" = "x300b" ];then
		modem_bus=`uci -q get glconfig.modem.bus | sed "s/[^0-9]/_/g"`
		name=`uci get network.modem_$modem_bus.ifname`
		proto=`uci get network.modem_$modem_bus.proto`
		#echo "name:$name proto:$proto" >/dev/console
		if [ "$proto" = "3g" ];then
			dev="${name}_${modem_bus}"
			sysdev=`uci get system.led_3gnet.dev`
			#echo "dev:$dev proto:$sysdev" >/dev/console
			if [ "$dev" != "" -a "$dev" != "$sysdev" ];then
				uci set system.led_3gnet.dev="$dev"
				flag=1
				#echo "dev:$dev" >/dev/console
			fi
		elif [ "$proto" = "qmi" -o "$proto" = "wwan" ];then
			#echo "name:$name proto:$proto" >/dev/console
			sysdev=`uci get system.led_3gnet.dev`
			if [ "$name" != "" -a "$name" != "$sysdev" ];then
				uci set system.led_3gnet.dev="$name"
				flag=1
				#echo "name:$name " >/dev/console
			fi
		else
			if [ "$name" != "" ];then
				uci set system.led_3gnet.dev="$name"
				flag=1
			fi
			#echo "aaa name:$name" >/dev/console
		fi
		if [ "$flag" = 1 ];then
			uci commit system
			/etc/init.d/system restart
		fi
	fi

}
